// 雅思核心词库 - 500词，按主题分类
const WORD_DB = [
// ===== ACADEMIC & EDUCATION =====
{en:"Analyse",ph:"/ˈænəlaɪz/",cn:"分析，研究",pos:"动词 v.",level:"雅思核心",topic:"学术",ex:{en:"Scientists analyse data to find patterns.",cn:"科学家分析数据以寻找规律。"},tip:"💡 英式拼写 analyse，美式 analyze<br>🔗 同族：analysis（n.分析）、analytical（adj.分析性的）",quiz:{q:"选出 analyse 的正确用法：",opts:["She analysed the results carefully.","She analysis the results.","She analytical the data.","She analysing always."],ans:0}},
{en:"Argument",ph:"/ˈɑːɡjumənt/",cn:"论点，争论，理由",pos:"名词 n.",level:"雅思核心",topic:"学术",ex:{en:"The essay presents a strong argument for renewable energy.",cn:"这篇文章提出了支持可再生能源的有力论点。"},tip:"💡 学术写作核心词！argument ≠ 吵架，更多指「论点」<br>🔗 同族：argue（v.）、argumentative（adj.好争辩的）",quiz:{q:"The essay presents a convincing ___.",opts:["argue","argument","argumentative","arguing"],ans:1}},
{en:"Concept",ph:"/ˈkɒnsept/",cn:"概念，观念，思想",pos:"名词 n.",level:"雅思核心",topic:"学术",ex:{en:"The concept of democracy has evolved over centuries.",cn:"民主的概念已经经历了几个世纪的演变。"},tip:"💡 词根：con（共同）+ cept（抓取）→ 共同抓住的想法<br>🔗 同族：conceive（v.构思）、conceptual（adj.概念的）",quiz:{q:"This is a difficult ___ to understand.",opts:["concept","conceive","conception","conceptual"],ans:0}},
{en:"Evaluate",ph:"/ɪˈvæljueɪt/",cn:"评估，评价，评定",pos:"动词 v.",level:"雅思核心",topic:"学术",ex:{en:"Teachers evaluate students' performance through exams.",cn:"老师通过考试评估学生的表现。"},tip:"💡 词根：e（出）+ valu（价值）+ ate → 评出价值<br>🔗 同族：evaluation（n.）、evaluative（adj.）",quiz:{q:"We need to ___ the risks carefully.",opts:["evaluation","evaluate","evaluative","evaluating always"],ans:1}},
{en:"Evidence",ph:"/ˈevɪdəns/",cn:"证据，证明，迹象",pos:"名词 n.",level:"雅思高频",topic:"学术",ex:{en:"There is strong evidence that exercise reduces stress.",cn:"有强有力的证据表明运动能减轻压力。"},tip:"💡 雅思写作必备：provide evidence（提供证据）<br>🔗 同族：evident（adj.明显的）、evidently（adv.）",quiz:{q:"Scientists found ___ to support their theory.",opts:["evident","evidently","evidence","evidenced"],ans:2}},
{en:"Theory",ph:"/ˈθɪəri/",cn:"理论，学说，推测",pos:"名词 n.",level:"雅思核心",topic:"学术",ex:{en:"Darwin's theory of evolution changed how we see life.",cn:"达尔文的进化论改变了我们对生命的看法。"},tip:"💡 in theory（理论上）vs in practice（实际上）<br>🔗 同族：theoretical（adj.）、theorist（n.理论家）",quiz:{q:"In ___, the plan sounds perfect.",opts:["theoretical","theorist","theory","theorize"],ans:2}},
{en:"Research",ph:"/rɪˈsɜːtʃ/",cn:"研究，调查，探究",pos:"名词/动词 n./v.",level:"雅思高频",topic:"学术",ex:{en:"Recent research shows that sleep affects memory.",cn:"最新研究表明睡眠会影响记忆力。"},tip:"💡 注意：research 通常不可数，不说 a research，说 a piece of research<br>🔗 同族：researcher（n.研究员）",quiz:{q:"哪句话是正确的？",opts:["She did a research on climate.","She did research on climate.","She did researches on climate.","She researched a research."],ans:1}},
{en:"Hypothesis",ph:"/haɪˈpɒθəsɪs/",cn:"假设，假说",pos:"名词 n.",level:"雅思学术",topic:"学术",ex:{en:"The scientist formed a hypothesis before conducting the experiment.",cn:"科学家在做实验前先提出了假说。"},tip:"💡 复数：hypotheses；动词：hypothesize<br>🔗 同族：hypothetical（adj.假设的）",quiz:{q:"The ___ was tested through experiments.",opts:["hypothetical","hypothesize","hypothesis","hypotheses"],ans:2}},
{en:"Acknowledge",ph:"/əkˈnɒlɪdʒ/",cn:"承认，致谢，确认",pos:"动词 v.",level:"雅思核心",topic:"学术",ex:{en:"We must acknowledge that climate change is a serious problem.",cn:"我们必须承认气候变化是一个严重的问题。"},tip:"💡 雅思写作高分词：acknowledge that... 承认...<br>🔗 同族：acknowledgement（n.承认/致谢）",quiz:{q:"We must ___ our mistakes.",opts:["acknowledgement","acknowledged","acknowledge","acknowledging"],ans:2}},
{en:"Curriculum",ph:"/kəˈrɪkjʊləm/",cn:"课程，课程计划",pos:"名词 n.",level:"雅思教育",topic:"学术",ex:{en:"The school curriculum includes science, maths, and languages.",cn:"学校课程包括科学、数学和语言。"},tip:"💡 复数：curricula 或 curriculums<br>🔗 相关：extracurricular（adj.课外的）",quiz:{q:"The national ___ was recently updated.",opts:["curriculums","curriculum","curricular","curricula"],ans:1}},

// ===== ENVIRONMENT =====
{en:"Sustainable",ph:"/səˈsteɪnəbl/",cn:"可持续的，环保的",pos:"形容词 adj.",level:"雅思高频",topic:"环境",ex:{en:"We need sustainable energy sources to protect the planet.",cn:"我们需要可持续能源来保护地球。"},tip:"💡 雅思环境话题核心词！sustainable development（可持续发展）<br>🔗 同族：sustain（v.维持）、sustainability（n.可持续性）",quiz:{q:"Solar power is a ___ energy source.",opts:["sustain","sustainability","sustainable","sustainably"],ans:2}},
{en:"Emission",ph:"/ɪˈmɪʃən/",cn:"排放，排放物",pos:"名词 n.",level:"雅思高频",topic:"环境",ex:{en:"Carbon emissions are the main cause of global warming.",cn:"碳排放是全球变暖的主要原因。"},tip:"💡 常用复数：emissions；carbon emissions（碳排放）<br>🔗 同族：emit（v.排放）、emitter（n.排放者）",quiz:{q:"The factory must reduce its ___.",opts:["emit","emitted","emission","emissions"],ans:3}},
{en:"Renewable",ph:"/rɪˈnjuːəbl/",cn:"可再生的，可更新的",pos:"形容词 adj.",level:"雅思高频",topic:"环境",ex:{en:"Renewable energy includes solar, wind, and hydroelectric power.",cn:"可再生能源包括太阳能、风能和水力发电。"},tip:"💡 反义词：non-renewable（不可再生的）<br>🔗 同族：renew（v.更新）、renewal（n.更新）",quiz:{q:"Wind power is a ___ energy source.",opts:["renew","renewal","renewable","renewed"],ans:2}},
{en:"Biodiversity",ph:"/ˌbaɪoʊdaɪˈvɜːrsɪti/",cn:"生物多样性",pos:"名词 n.",level:"雅思环境",topic:"环境",ex:{en:"Deforestation threatens biodiversity in tropical rainforests.",cn:"森林砍伐威胁着热带雨林的生物多样性。"},tip:"💡 bio（生命）+ diversity（多样性）→ 生命的多样性<br>🔗 相关：ecosystem（生态系统）、habitat（栖息地）",quiz:{q:"Pollution damages ___.",opts:["biodiversify","biodiverse","biodiversity","biodiversities"],ans:2}},
{en:"Contaminate",ph:"/kənˈtæmɪneɪt/",cn:"污染，弄脏，使受污染",pos:"动词 v.",level:"雅思环境",topic:"环境",ex:{en:"Industrial waste can contaminate rivers and harm wildlife.",cn:"工业废物会污染河流并危害野生动物。"},tip:"💡 比 pollute 更强调「毒素/有害物质」的污染<br>🔗 同族：contamination（n.）、contaminant（n.污染物）",quiz:{q:"Chemicals ___ the drinking water.",opts:["contamination","contaminated","contaminate","contaminant"],ans:1}},
{en:"Deforestation",ph:"/ˌdiːˌfɒrɪˈsteɪʃən/",cn:"森林砍伐，滥伐森林",pos:"名词 n.",level:"雅思高频",topic:"环境",ex:{en:"Deforestation in the Amazon is accelerating at an alarming rate.",cn:"亚马逊的森林砍伐正在以惊人的速度加速。"},tip:"💡 de（去除）+ forest（森林）+ ation → 去除森林<br>🔗 反义词：reforestation（重新造林）",quiz:{q:"___ destroys animal habitats.",opts:["Deforest","Deforestation","Deforested","Deforesting"],ans:1}},
{en:"Ecosystem",ph:"/ˈiːkəʊˌsɪstəm/",cn:"生态系统",pos:"名词 n.",level:"雅思核心",topic:"环境",ex:{en:"The coral reef ecosystem supports thousands of species.",cn:"珊瑚礁生态系统支撑着数千种生物。"},tip:"💡 eco（生态）+ system（系统）<br>🔗 相关：ecology（生态学）、ecological（adj.生态的）",quiz:{q:"Pollution disrupts the natural ___.",opts:["ecology","ecological","ecosystem","ecosystems"],ans:2}},
{en:"Greenhouse",ph:"/ˈɡriːnhaʊs/",cn:"温室；温室效应的",pos:"名词/形容词 n./adj.",level:"雅思高频",topic:"环境",ex:{en:"Greenhouse gases trap heat in the atmosphere.",cn:"温室气体将热量困在大气层中。"},tip:"💡 greenhouse effect（温室效应）；greenhouse gas（温室气体）<br>🔗 相关：global warming（全球变暖）",quiz:{q:"CO₂ is a ___ gas.",opts:["greenhouse","green house","greening","greened"],ans:0}},
{en:"Conservation",ph:"/ˌkɒnsəˈveɪʃən/",cn:"保护，保存，节约",pos:"名词 n.",level:"雅思核心",topic:"环境",ex:{en:"Wildlife conservation is essential for maintaining biodiversity.",cn:"野生动物保护对维持生物多样性至关重要。"},tip:"💡 conservation of energy（能量守恒）；wildlife conservation（野生动物保护）<br>🔗 同族：conserve（v.）、conservative（adj.保守的）",quiz:{q:"___ efforts have saved many endangered species.",opts:["Conserve","Conservative","Conservation","Conservatory"],ans:2}},
{en:"Pollution",ph:"/pəˈluːʃən/",cn:"污染，公害",pos:"名词 n.",level:"雅思高频",topic:"环境",ex:{en:"Air pollution in cities is linked to respiratory diseases.",cn:"城市空气污染与呼吸道疾病有关。"},tip:"💡 种类：air/water/noise/light/soil pollution<br>🔗 同族：pollute（v.）、pollutant（n.污染物）、polluter（n.）",quiz:{q:"The river suffers from severe water ___.",opts:["pollute","pollutant","pollution","polluted"],ans:2}},

// ===== TECHNOLOGY =====
{en:"Innovation",ph:"/ˌɪnəˈveɪʃən/",cn:"创新，革新，新事物",pos:"名词 n.",level:"雅思高频",topic:"科技",ex:{en:"Technological innovation has transformed the way we communicate.",cn:"技术创新改变了我们的沟通方式。"},tip:"💡 词根：innov（新的）+ ation → 带来新的东西<br>🔗 同族：innovate（v.）、innovative（adj.创新的）、innovator（n.）",quiz:{q:"The company is known for its ___.",opts:["innovate","innovative","innovation","innovator"],ans:2}},
{en:"Artificial",ph:"/ˌɑːtɪˈfɪʃəl/",cn:"人工的，人造的，不自然的",pos:"形容词 adj.",level:"雅思核心",topic:"科技",ex:{en:"Artificial intelligence is changing the job market rapidly.",cn:"人工智能正在迅速改变就业市场。"},tip:"💡 artificial intelligence（AI 人工智能）<br>🔗 反义词：natural（自然的）；同族：artificially（adv.）",quiz:{q:"___ intelligence can process data faster than humans.",opts:["Artificially","Artifact","Artificial","Artifice"],ans:2}},
{en:"Algorithm",ph:"/ˈælɡərɪðəm/",cn:"算法，计算程序",pos:"名词 n.",level:"雅思科技",topic:"科技",ex:{en:"Social media algorithms decide what content you see.",cn:"社交媒体算法决定你看到什么内容。"},tip:"💡 现代科技必备词，来自阿拉伯数学家 Al-Khwarizmi 的名字<br>🔗 相关：data（数据）、code（代码）",quiz:{q:"The ___ recommends videos based on your history.",opts:["algorithm","algorithmic","algorithmically","algorithms"],ans:0}},
{en:"Automation",ph:"/ˌɔːtəˈmeɪʃən/",cn:"自动化，自动操作",pos:"名词 n.",level:"雅思高频",topic:"科技",ex:{en:"Automation in factories has replaced many manual jobs.",cn:"工厂自动化取代了许多体力劳动岗位。"},tip:"💡 auto（自动）+ mation → 自动运作<br>🔗 同族：automate（v.使自动化）、automated（adj.自动化的）",quiz:{q:"___ has increased factory productivity.",opts:["Automate","Automated","Automation","Automatic"],ans:2}},
{en:"Digital",ph:"/ˈdɪdʒɪtəl/",cn:"数字的，数码的",pos:"形容词 adj.",level:"雅思高频",topic:"科技",ex:{en:"The digital revolution has changed how we access information.",cn:"数字革命改变了我们获取信息的方式。"},tip:"💡 digital divide（数字鸿沟）；digital literacy（数字素养）<br>🔗 反义词：analogue（模拟的）",quiz:{q:"We live in a ___ age.",opts:["digit","digitally","digital","digitalize"],ans:2}},
{en:"Surveillance",ph:"/səˈveɪləns/",cn:"监视，监控，监察",pos:"名词 n.",level:"雅思科技",topic:"科技",ex:{en:"CCTV surveillance cameras are installed throughout the city.",cn:"闭路电视监控摄像头安装在整个城市。"},tip:"💡 雅思隐私话题高频词！mass surveillance（大规模监控）<br>🔗 相关：privacy（隐私）、data protection（数据保护）",quiz:{q:"The government uses ___ cameras to monitor crime.",opts:["surveille","surveillance","surveillant","surveilling"],ans:1}},
{en:"Infrastructure",ph:"/ˈɪnfrəˌstrʌktʃə/",cn:"基础设施，基础结构",pos:"名词 n.",level:"雅思核心",topic:"科技",ex:{en:"Developing countries need to invest in digital infrastructure.",cn:"发展中国家需要投资数字基础设施。"},tip:"💡 infra（下面）+ structure（结构）→ 支撑一切的底层结构<br>🔗 相关：transport infrastructure（交通基础设施）",quiz:{q:"The city needs to improve its transport ___.",opts:["infrastructural","infrastructure","infrastructures","infrastracture"],ans:1}},
{en:"Obsolete",ph:"/ˌɒbsəˈliːt/",cn:"过时的，废弃的，淘汰的",pos:"形容词 adj.",level:"雅思科技",topic:"科技",ex:{en:"Many traditional skills have become obsolete due to technology.",cn:"由于技术的发展，许多传统技能已经过时。"},tip:"💡 become obsolete = 被淘汰；make obsolete = 使...淘汰<br>🔗 同义词：outdated, outmoded, redundant",quiz:{q:"Fax machines have become ___.",opts:["obsoletely","obsolescence","obsolete","obsoleted"],ans:2}},
{en:"Cybersecurity",ph:"/ˌsaɪbəsɪˈkjʊərɪti/",cn:"网络安全",pos:"名词 n.",level:"雅思科技",topic:"科技",ex:{en:"Cybersecurity threats are becoming more sophisticated every year.",cn:"网络安全威胁每年都变得更加复杂。"},tip:"💡 cyber（网络）+ security（安全）<br>🔗 相关：hacker（黑客）、data breach（数据泄露）",quiz:{q:"Companies invest heavily in ___ to protect data.",opts:["cybersecurity","cybersecure","cybersecured","cyber security system"],ans:0}},
{en:"Virtual",ph:"/ˈvɜːtʃuəl/",cn:"虚拟的，实质上的",pos:"形容词 adj.",level:"雅思核心",topic:"科技",ex:{en:"Virtual reality technology is used in gaming and education.",cn:"虚拟现实技术被用于游戏和教育。"},tip:"💡 virtual reality（VR虚拟现实）；virtually（adv.几乎，实际上）<br>🔗 同族：virtually（adv.）",quiz:{q:"___ meetings have replaced many in-person ones.",opts:["Virtually","Virtue","Virtual","Virtualize"],ans:2}},

// ===== SOCIETY & CULTURE =====
{en:"Urbanisation",ph:"/ˌɜːbənaɪˈzeɪʃən/",cn:"城市化，都市化",pos:"名词 n.",level:"雅思高频",topic:"社会",ex:{en:"Rapid urbanisation has led to overcrowding in major cities.",cn:"快速城市化导致大城市人口过多。"},tip:"💡 英式拼写：urbanisation；美式：urbanization<br>🔗 同族：urban（adj.城市的）、urbanise（v.）",quiz:{q:"___ has caused housing shortages in cities.",opts:["Urban","Urbanise","Urbanisation","Urbanised"],ans:2}},
{en:"Diversity",ph:"/daɪˈvɜːsɪti/",cn:"多样性，差异性",pos:"名词 n.",level:"雅思高频",topic:"社会",ex:{en:"Cultural diversity enriches society and promotes understanding.",cn:"文化多样性丰富了社会并促进了相互理解。"},tip:"💡 diversity and inclusion（多元与包容）<br>🔗 同族：diverse（adj.多样的）、diversify（v.使多样化）",quiz:{q:"The city celebrates its cultural ___.",opts:["diverse","diversify","diversity","diversification"],ans:2}},
{en:"Inequality",ph:"/ˌɪnɪˈkwɒlɪti/",cn:"不平等，不均等",pos:"名词 n.",level:"雅思高频",topic:"社会",ex:{en:"Income inequality between rich and poor has widened.",cn:"贫富之间的收入不平等已经扩大。"},tip:"💡 in（不）+ equality（平等）→ 不平等<br>🔗 同族：unequal（adj.）、inequitable（adj.不公平的）",quiz:{q:"Gender ___ remains a global issue.",opts:["unequal","inequitable","inequality","inequal"],ans:2}},
{en:"Migration",ph:"/maɪˈɡreɪʃən/",cn:"移民，迁移，移居",pos:"名词 n.",level:"雅思高频",topic:"社会",ex:{en:"Economic migration has increased significantly in recent decades.",cn:"近几十年来，经济性移民大幅增加。"},tip:"💡 immigration（移入）vs emigration（移出）vs migration（统称）<br>🔗 同族：migrate（v.）、migrant（n.移民）",quiz:{q:"___ from rural to urban areas is common.",opts:["Migrate","Migrant","Migration","Migratory"],ans:2}},
{en:"Demographic",ph:"/ˌdeməˈɡræfɪk/",cn:"人口统计的；人口特征",pos:"形容词/名词 adj./n.",level:"雅思社会",topic:"社会",ex:{en:"Demographic changes are affecting pension systems worldwide.",cn:"人口结构变化正在影响全球养老金体系。"},tip:"💡 demo（人民）+ graphic（描写）→ 描述人口的<br>🔗 同族：demography（n.人口学）、demographics（n.人口统计数据）",quiz:{q:"___ data shows an ageing population.",opts:["Demography","Demographic","Demographics","Demographer"],ans:1}},
{en:"Prejudice",ph:"/ˈpredʒudɪs/",cn:"偏见，成见，歧视",pos:"名词/动词 n./v.",level:"雅思社会",topic:"社会",ex:{en:"Racial prejudice continues to be a problem in many societies.",cn:"种族偏见在许多社会中仍然是一个问题。"},tip:"💡 pre（之前）+ judice（判断）→ 预先判断 → 偏见<br>🔗 同族：prejudiced（adj.有偏见的）、unprejudiced（adj.无偏见的）",quiz:{q:"We should fight against ___ and discrimination.",opts:["prejudiced","prejudice","prejudging","prejudicial"],ans:1}},
{en:"Stereotype",ph:"/ˈsteriəˌtaɪp/",cn:"刻板印象，模式化观念",pos:"名词/动词 n./v.",level:"雅思社会",topic:"社会",ex:{en:"We should avoid reinforcing negative stereotypes about any group.",cn:"我们应该避免强化对任何群体的负面刻板印象。"},tip:"💡 stereo（固定的）+ type（类型）→ 固定的类型 → 刻板印象<br>🔗 同族：stereotypical（adj.）、stereotype（v.对...产生刻板印象）",quiz:{q:"Gender ___ limit people's opportunities.",opts:["stereotyping","stereotypes","stereotype","stereotypical"],ans:1}},
{en:"Integration",ph:"/ˌɪntɪˈɡreɪʃən/",cn:"融合，整合，一体化",pos:"名词 n.",level:"雅思社会",topic:"社会",ex:{en:"The integration of immigrants into society requires time and effort.",cn:"移民融入社会需要时间和努力。"},tip:"💡 integrate（v.整合）→ integration（n.）<br>🔗 相关：social cohesion（社会凝聚力）",quiz:{q:"Successful ___ requires mutual respect.",opts:["integrate","integrated","integration","integrative"],ans:2}},
{en:"Welfare",ph:"/ˈwelfeə/",cn:"福利，幸福，健康",pos:"名词 n.",level:"雅思核心",topic:"社会",ex:{en:"The government spends billions on social welfare programmes.",cn:"政府在社会福利项目上花费数十亿。"},tip:"💡 social welfare（社会福利）；animal welfare（动物福利）<br>🔗 相关：well-being（幸福感）",quiz:{q:"Child ___ should be the government's priority.",opts:["well","welfare","welfaring","welfarism"],ans:1}},
{en:"Legislation",ph:"/ˌledʒɪˈsleɪʃən/",cn:"立法，法律，法规",pos:"名词 n.",level:"雅思核心",topic:"社会",ex:{en:"New legislation has been introduced to protect workers' rights.",cn:"新法律已被引入以保护工人的权利。"},tip:"💡 legislate（v.立法）→ legislation（n.法律）<br>🔗 同族：legislator（n.立法者）、legislative（adj.立法的）",quiz:{q:"The government passed new ___ on data privacy.",opts:["legislate","legislative","legislation","legislator"],ans:2}},

// ===== HEALTH =====
{en:"Obesity",ph:"/əʊˈbiːsɪti/",cn:"肥胖症，过度肥胖",pos:"名词 n.",level:"雅思高频",topic:"健康",ex:{en:"Childhood obesity is increasing due to poor diet and lack of exercise.",cn:"由于饮食不良和缺乏运动，儿童肥胖症正在增加。"},tip:"💡 obese（adj.肥胖的）→ obesity（n.）<br>🔗 相关：overweight（超重）、malnourished（营养不良的）",quiz:{q:"___ is linked to heart disease and diabetes.",opts:["Obese","Obesity","Obesian","Obesely"],ans:1}},
{en:"Mental",ph:"/ˈmentəl/",cn:"精神的，心理的，智力的",pos:"形容词 adj.",level:"雅思高频",topic:"健康",ex:{en:"Mental health issues affect millions of people worldwide.",cn:"心理健康问题影响着全球数百万人。"},tip:"💡 mental health（心理健康）；mental illness（精神疾病）<br>🔗 同族：mentality（n.心态）、mentally（adv.）",quiz:{q:"___ health is as important as physical health.",opts:["Mentality","Mentally","Mental","Mind"],ans:2}},
{en:"Epidemic",ph:"/ˌepɪˈdemɪk/",cn:"流行病，盛行，泛滥",pos:"名词/形容词 n./adj.",level:"雅思健康",topic:"健康",ex:{en:"The obesity epidemic is a major public health challenge.",cn:"肥胖症流行是一个主要的公共卫生挑战。"},tip:"💡 epi（在...之上）+ demo（人群）→ 在人群中蔓延<br>🔗 区别：epidemic（流行病，局部）vs pandemic（大流行，全球）",quiz:{q:"The flu ___ spread rapidly through schools.",opts:["epidemically","epidemiologist","epidemic","epidemics"],ans:2}},
{en:"Sedentary",ph:"/ˈsedəntri/",cn:"久坐的，不活跃的",pos:"形容词 adj.",level:"雅思健康",topic:"健康",ex:{en:"A sedentary lifestyle increases the risk of heart disease.",cn:"久坐不动的生活方式会增加患心脏病的风险。"},tip:"💡 sedent（坐）+ ary → 总是坐着的<br>🔗 反义词：active（积极活跃的）",quiz:{q:"Office workers often lead ___ lifestyles.",opts:["sediment","sedentarily","sedentary","sedentarism"],ans:2}},
{en:"Nutrition",ph:"/njuːˈtrɪʃən/",cn:"营养，营养学",pos:"名词 n.",level:"雅思核心",topic:"健康",ex:{en:"Good nutrition is essential for children's physical development.",cn:"良好的营养对儿童的身体发育至关重要。"},tip:"💡 nutritious（adj.有营养的）；nutritionist（n.营养师）<br>🔗 同族：nutrient（n.营养物质）、malnourishment（n.营养不良）",quiz:{q:"Children need proper ___ to grow healthily.",opts:["nutritious","nutritionist","nutrition","nutrient"],ans:2}},
{en:"Pandemic",ph:"/pænˈdemɪk/",cn:"大流行病，全球性流行",pos:"名词/形容词 n./adj.",level:"雅思健康",topic:"健康",ex:{en:"The COVID-19 pandemic affected every country in the world.",cn:"新冠疫情影响了世界上的每个国家。"},tip:"💡 pan（全部）+ demo（人群）→ 全人群中蔓延<br>🔗 区别：endemic（地方性的）、epidemic（流行性的）、pandemic（全球性的）",quiz:{q:"The WHO declared a global ___.",opts:["epidemic","endemic","pandemic","pandemically"],ans:2}},
{en:"Therapeutic",ph:"/ˌθerəˈpjuːtɪk/",cn:"治疗的，有疗效的",pos:"形容词 adj.",level:"雅思健康",topic:"健康",ex:{en:"Music has been shown to have therapeutic benefits for mental health.",cn:"音乐已被证明对心理健康有治疗效果。"},tip:"💡 therapy（n.治疗）→ therapeutic（adj.）<br>🔗 同族：therapist（n.治疗师）、therapy（n.疗法）",quiz:{q:"Exercise has ___ benefits for depression.",opts:["therapy","therapist","therapeutic","therapeutically"],ans:2}},
{en:"Preventable",ph:"/prɪˈventəbl/",cn:"可预防的，可避免的",pos:"形容词 adj.",level:"雅思健康",topic:"健康",ex:{en:"Many diseases are preventable through vaccination and healthy habits.",cn:"许多疾病可以通过疫苗接种和健康习惯来预防。"},tip:"💡 prevent（v.预防）→ preventable（adj.可预防的）<br>🔗 同族：prevention（n.预防）、preventive（adj.预防性的）",quiz:{q:"Diabetes is often a ___ disease.",opts:["prevent","prevention","preventive","preventable"],ans:3}},
{en:"Immune",ph:"/ɪˈmjuːn/",cn:"免疫的，有免疫力的",pos:"形容词 adj.",level:"雅思健康",topic:"健康",ex:{en:"Vaccines help the body develop an immune response to diseases.",cn:"疫苗帮助身体对疾病产生免疫反应。"},tip:"💡 immune system（免疫系统）；immune to（对...免疫）<br>🔗 同族：immunity（n.免疫力）、immunise（v.使免疫）",quiz:{q:"The vaccine strengthens the ___ system.",opts:["immunity","immunise","immune","immunology"],ans:2}},
{en:"Rehabilitation",ph:"/ˌriːəˌbɪlɪˈteɪʃən/",cn:"康复，恢复，复原",pos:"名词 n.",level:"雅思健康",topic:"健康",ex:{en:"Physical rehabilitation helps patients recover after surgery.",cn:"物理康复帮助患者在手术后恢复。"},tip:"💡 re（重新）+ habilit（能力）+ ation → 重新获得能力<br>🔗 同族：rehabilitate（v.使康复）、rehab（口语缩写）",quiz:{q:"The athlete underwent ___ after breaking his leg.",opts:["rehabilitate","rehabilitated","rehabilitation","rehabilitating"],ans:2}},

// ===== ECONOMICS =====
{en:"Globalisation",ph:"/ˌɡləʊbəlaɪˈzeɪʃən/",cn:"全球化",pos:"名词 n.",level:"雅思高频",topic:"经济",ex:{en:"Globalisation has created both opportunities and challenges for economies.",cn:"全球化为经济创造了机遇，同时也带来了挑战。"},tip:"💡 英式 globalisation；美式 globalization<br>🔗 同族：global（adj.全球的）、globalise（v.）",quiz:{q:"___ has increased trade between countries.",opts:["Global","Globalise","Globalisation","Globally"],ans:2}},
{en:"Inflation",ph:"/ɪnˈfleɪʃən/",cn:"通货膨胀，物价上涨",pos:"名词 n.",level:"雅思核心",topic:"经济",ex:{en:"High inflation reduces people's purchasing power.",cn:"高通货膨胀率降低了人们的购买力。"},tip:"💡 inflate（v.充气/膨胀）→ inflation（n.）<br>🔗 反义词：deflation（通货紧缩）",quiz:{q:"Rising ___ makes everyday goods more expensive.",opts:["inflate","inflated","inflation","inflationary"],ans:2}},
{en:"Entrepreneur",ph:"/ˌɒntrəprəˈnɜː/",cn:"企业家，创业者",pos:"名词 n.",level:"雅思经济",topic:"经济",ex:{en:"Young entrepreneurs are driving innovation in the tech industry.",cn:"年轻的企业家正在推动科技行业的创新。"},tip:"💡 来自法语，entre（之间）+ prendre（拿取）→ 在机会中创业<br>🔗 同族：entrepreneurship（n.创业精神）",quiz:{q:"She became a successful ___ at the age of 25.",opts:["entrepreneurship","entrepreneur","entrepreneurial","entrepreneurs"],ans:1}},
{en:"Investment",ph:"/ɪnˈvestmənt/",cn:"投资，投入",pos:"名词 n.",level:"雅思核心",topic:"经济",ex:{en:"Foreign investment has boosted the country's economic growth.",cn:"外国投资促进了该国的经济增长。"},tip:"💡 invest（v.投资）→ investment（n.）<br>🔗 同族：investor（n.投资者）、invest in（投资于）",quiz:{q:"The government increased ___ in education.",opts:["invest","investor","investment","investing"],ans:2}},
{en:"Poverty",ph:"/ˈpɒvəti/",cn:"贫穷，贫困",pos:"名词 n.",level:"雅思高频",topic:"经济",ex:{en:"Extreme poverty affects over 700 million people globally.",cn:"极端贫困影响着全球超过7亿人。"},tip:"💡 poverty line（贫困线）；poverty trap（贫困陷阱）<br>🔗 同族：poor（adj.）、impoverish（v.使贫困）",quiz:{q:"Education can help people escape ___.",opts:["poor","impoverish","poverty","povertous"],ans:2}},
{en:"Monopoly",ph:"/məˈnɒpəli/",cn:"垄断，专卖权",pos:"名词 n.",level:"雅思经济",topic:"经济",ex:{en:"Large corporations can create monopolies that harm consumers.",cn:"大公司可能会创建损害消费者利益的垄断。"},tip:"💡 mono（单一）+ poly（销售）→ 单一销售 → 垄断<br>🔗 同族：monopolise（v.垄断）、monopolistic（adj.垄断性的）",quiz:{q:"The company has a ___ over the local market.",opts:["monopolise","monopoly","monopolistic","monopolies"],ans:1}},
{en:"Expenditure",ph:"/ɪkˈspendɪtʃə/",cn:"支出，花费，开销",pos:"名词 n.",level:"雅思经济",topic:"经济",ex:{en:"Government expenditure on healthcare has increased significantly.",cn:"政府在医疗保健方面的支出大幅增加。"},tip:"💡 比 spending 更正式；public expenditure（公共支出）<br>🔗 同族：expend（v.花费）、expendable（adj.可消耗的）",quiz:{q:"Military ___ takes a large share of the budget.",opts:["expend","expense","expenditure","expended"],ans:2}},
{en:"Commodity",ph:"/kəˈmɒdɪti/",cn:"商品，货物，原料",pos:"名词 n.",level:"雅思经济",topic:"经济",ex:{en:"Oil is one of the most valuable commodities in the world.",cn:"石油是世界上最有价值的商品之一。"},tip:"💡 commodity prices（大宗商品价格）<br>🔗 相关：goods（货物）、merchandise（商品）",quiz:{q:"Gold is a valuable ___.",opts:["commodify","commodious","commodity","commodities"],ans:2}},
{en:"Subsidy",ph:"/ˈsʌbsɪdi/",cn:"补贴，津贴，资助",pos:"名词 n.",level:"雅思经济",topic:"经济",ex:{en:"Government subsidies help farmers survive difficult economic times.",cn:"政府补贴帮助农民度过艰难的经济时期。"},tip:"💡 subsidise（v.补贴）；farm subsidy（农业补贴）<br>🔗 同族：subsidise（v.给予补贴）、subsidised（adj.受补贴的）",quiz:{q:"The government provides ___ for renewable energy.",opts:["subsidise","subsidised","subsidy","subsidies"],ans:2}},
{en:"Unemployment",ph:"/ˌʌnɪmˈplɔɪmənt/",cn:"失业，失业率",pos:"名词 n.",level:"雅思高频",topic:"经济",ex:{en:"High unemployment leads to increased poverty and social problems.",cn:"高失业率导致贫困和社会问题增加。"},tip:"💡 unemployment rate（失业率）；youth unemployment（青年失业）<br>🔗 同族：unemployed（adj.失业的）、employ（v.雇用）",quiz:{q:"The ___ rate rose during the economic crisis.",opts:["employ","unemployed","unemployment","employer"],ans:2}},

// ===== GOVERNMENT & POLITICS =====
{en:"Democracy",ph:"/dɪˈmɒkrəsi/",cn:"民主，民主制度",pos:"名词 n.",level:"雅思高频",topic:"政治",ex:{en:"Democracy requires an informed and engaged citizenry.",cn:"民主需要有见识且积极参与的公民。"},tip:"💡 demo（人民）+ cracy（统治）→ 人民统治<br>🔗 同族：democratic（adj.民主的）、democrat（n.民主人士）",quiz:{q:"Free elections are essential to ___.",opts:["democratic","democrat","democracy","democratise"],ans:2}},
{en:"Policy",ph:"/ˈpɒlɪsi/",cn:"政策，方针，策略",pos:"名词 n.",level:"雅思高频",topic:"政治",ex:{en:"The government introduced new policies to combat climate change.",cn:"政府出台了新政策来应对气候变化。"},tip:"💡 policy vs politics：policy（政策/策略）；politics（政治）<br>🔗 相关：implement a policy（实施政策）、policy maker（政策制定者）",quiz:{q:"The new tax ___ has been widely criticised.",opts:["politics","political","policy","policeman"],ans:2}},
{en:"Corruption",ph:"/kəˈrʌpʃən/",cn:"腐败，贪污，堕落",pos:"名词 n.",level:"雅思高频",topic:"政治",ex:{en:"Corruption undermines trust in government institutions.",cn:"腐败破坏了人们对政府机构的信任。"},tip:"💡 corrupt（adj.腐败的）→ corruption（n.）<br>🔗 同族：corrupt（v.腐化）、anti-corruption（反腐）",quiz:{q:"___ is a major obstacle to development.",opts:["corrupt","corrupted","corruption","corruptly"],ans:2}},
{en:"Constitution",ph:"/ˌkɒnstɪˈtjuːʃən/",cn:"宪法，章程，体质",pos:"名词 n.",level:"雅思政治",topic:"政治",ex:{en:"The constitution guarantees equal rights for all citizens.",cn:"宪法保障所有公民的平等权利。"},tip:"💡 constitute（v.构成）→ constitution（n.）<br>🔗 同族：constitutional（adj.宪法的）",quiz:{q:"The ___ protects freedom of speech.",opts:["constitute","constitutional","constitution","constitutionally"],ans:2}},
{en:"Transparency",ph:"/trænsˈpærənsi/",cn:"透明度，透明性",pos:"名词 n.",level:"雅思政治",topic:"政治",ex:{en:"Transparency in government builds public trust.",cn:"政府的透明度建立公众信任。"},tip:"💡 transparent（adj.透明的）→ transparency（n.）<br>🔗 相关：accountability（n.问责制）",quiz:{q:"Financial ___ is required of all public companies.",opts:["transparent","transparently","transparency","transparencies"],ans:2}},
{en:"Authoritarian",ph:"/ɔːˌθɒrɪˈteəriən/",cn:"权威主义的，独裁的",pos:"形容词/名词 adj./n.",level:"雅思政治",topic:"政治",ex:{en:"Authoritarian governments often restrict freedom of speech.",cn:"威权政府通常限制言论自由。"},tip:"💡 authority（权威）→ authoritarian（威权主义的）<br>🔗 反义词：democratic（民主的）、liberal（自由主义的）",quiz:{q:"The ___ regime silenced opposition voices.",opts:["authoritative","authoritarian","authority","authorize"],ans:1}},
{en:"Referendum",ph:"/ˌrefəˈrendəm/",cn:"公投，全民公决",pos:"名词 n.",level:"雅思政治",topic:"政治",ex:{en:"The country held a referendum on whether to join the EU.",cn:"该国就是否加入欧盟举行了公投。"},tip:"💡 来自拉丁语，refer（提交）+ endum → 提交给人民决定<br>🔗 复数：referenda 或 referendums",quiz:{q:"The government called a ___ on the new law.",opts:["referral","referendum","reference","referendums"],ans:1}},
{en:"Sovereignty",ph:"/ˈsɒvrɪnti/",cn:"主权，自治权",pos:"名词 n.",level:"雅思政治",topic:"政治",ex:{en:"National sovereignty means a country's right to govern itself.",cn:"国家主权意味着一个国家自我治理的权利。"},tip:"💡 sovereign（n.君主/adj.主权的）→ sovereignty（n.主权）<br>🔗 相关：autonomy（自治）、independence（独立）",quiz:{q:"The treaty respects each nation's ___.",opts:["sovereign","sovereignty","sovereignly","sovereignties"],ans:1}},
{en:"Diplomacy",ph:"/dɪˈpləʊməsi/",cn:"外交，外交手腕",pos:"名词 n.",level:"雅思政治",topic:"政治",ex:{en:"Diplomacy is essential for resolving international conflicts peacefully.",cn:"外交对于和平解决国际冲突至关重要。"},tip:"💡 diplomat（n.外交官）→ diplomacy（n.外交）<br>🔗 同族：diplomatic（adj.外交的）、diplomatically（adv.）",quiz:{q:"The two countries resolved the dispute through ___.",opts:["diplomat","diplomatic","diplomacy","diplomatically"],ans:2}},
{en:"Sanction",ph:"/ˈsæŋkʃən/",cn:"制裁；批准，认可",pos:"名词/动词 n./v.",level:"雅思政治",topic:"政治",ex:{en:"International sanctions were imposed on the country.",cn:"国际制裁被强加于该国。"},tip:"💡 双重含义：1.制裁（惩罚）2.批准（许可）<br>🔗 economic sanctions（经济制裁）",quiz:{q:"The UN imposed ___ on the country.",opts:["sanctioned","sanction","sanctions","sanctioning"],ans:2}},

// ===== EDUCATION =====
{en:"Compulsory",ph:"/kəmˈpʌlsəri/",cn:"强制的，义务的，必修的",pos:"形容词 adj.",level:"雅思核心",topic:"教育",ex:{en:"Education is compulsory for children between the ages of 5 and 16.",cn:"5至16岁的儿童必须接受义务教育。"},tip:"💡 compel（v.强迫）→ compulsory（adj.）<br>🔗 同义词：mandatory, obligatory；反义词：optional, voluntary",quiz:{q:"Maths is a ___ subject in most schools.",opts:["compelled","compulsion","compulsory","compulsorily"],ans:2}},
{en:"Literacy",ph:"/ˈlɪtərəsi/",cn:"读写能力，文化素养",pos:"名词 n.",level:"雅思高频",topic:"教育",ex:{en:"Digital literacy is becoming as important as reading and writing.",cn:"数字素养正在变得与读写一样重要。"},tip:"💡 literate（adj.有文化的）→ literacy（n.）<br>🔗 同族：illiteracy（n.文盲）、literate（adj.有读写能力的）",quiz:{q:"___ rates have improved dramatically in developing countries.",opts:["Literate","Literary","Literacy","Literature"],ans:2}},
{en:"Vocational",ph:"/vəʊˈkeɪʃənəl/",cn:"职业的，职业培训的",pos:"形容词 adj.",level:"雅思教育",topic:"教育",ex:{en:"Vocational training prepares students for specific careers.",cn:"职业培训为学生准备特定职业。"},tip:"💡 vocation（n.职业/天职）→ vocational（adj.）<br>🔗 vocational school（职业学校）；vocational training（职业培训）",quiz:{q:"___ courses teach practical skills for work.",opts:["Vocation","Vocational","Vocationally","Vocations"],ans:1}},
{en:"Scholarship",ph:"/ˈskɒləʃɪp/",cn:"奖学金；学问，学识",pos:"名词 n.",level:"雅思核心",topic:"教育",ex:{en:"She received a scholarship to study at Oxford University.",cn:"她获得了在牛津大学学习的奖学金。"},tip:"💡 scholar（n.学者）+ ship（状态）→ 学者的状态 → 奖学金/学识<br>🔗 同族：scholarly（adj.学术的）、scholar（n.学者）",quiz:{q:"He won a full ___ to study abroad.",opts:["scholarly","scholar","scholarship","schoolship"],ans:2}},
{en:"Tuition",ph:"/tjuːˈɪʃən/",cn:"学费；教学，辅导",pos:"名词 n.",level:"雅思核心",topic:"教育",ex:{en:"University tuition fees have increased significantly in recent years.",cn:"近年来大学学费大幅上涨。"},tip:"💡 tuition fees（学费）；private tuition（私人辅导）<br>🔗 同族：tutor（n.导师/v.辅导）",quiz:{q:"___ fees at private universities can be very high.",opts:["Tutor","Tutorial","Tuition","Teaching"],ans:2}},

// ===== WRITING CONNECTORS =====
{en:"Nevertheless",ph:"/ˌnevəðəˈles/",cn:"尽管如此，然而，不过",pos:"副词 adv.",level:"雅思写作",topic:"连接词",ex:{en:"The task was difficult; nevertheless, she completed it successfully.",cn:"任务很困难；尽管如此，她还是成功完成了。"},tip:"💡 表让步转折，比 but 更正式<br>🔗 同义词：nonetheless, however, yet, still",quiz:{q:"The plan had flaws; ___, it was approved.",opts:["nevertheless","never","nevermore","neverless"],ans:0}},
{en:"Moreover",ph:"/mɔːˈrəʊvə/",cn:"此外，而且，再者",pos:"副词 adv.",level:"雅思写作",topic:"连接词",ex:{en:"Exercise improves health. Moreover, it boosts mental well-being.",cn:"运动改善健康。此外，它还能提升心理健康。"},tip:"💡 表递进，比 furthermore 语气稍弱<br>🔗 同义词：furthermore, in addition, additionally",quiz:{q:"The hotel is cheap. ___, it's in a great location.",opts:["Moreover","More over","Moreoever","Moreso"],ans:0}},
{en:"Conversely",ph:"/ˈkɒnvɜːsli/",cn:"相反地，反过来说",pos:"副词 adv.",level:"雅思写作",topic:"连接词",ex:{en:"Some people prefer cities; conversely, others love rural life.",cn:"有些人喜欢城市；相反，另一些人热爱农村生活。"},tip:"💡 表对比，雅思讨论两种观点时必备<br>🔗 同义词：on the contrary, in contrast, by contrast",quiz:{q:"Rich countries consume more. ___, poor nations use fewer resources.",opts:["Conversely","Conversally","Contrarily","Conversely so"],ans:0}},
{en:"Consequently",ph:"/ˈkɒnsɪkwəntli/",cn:"因此，结果",pos:"副词 adv.",level:"雅思写作",topic:"连接词",ex:{en:"She trained hard; consequently, she won the competition.",cn:"她刻苦训练；因此，她赢得了比赛。"},tip:"💡 表因果，比 so 更正式<br>🔗 同义词：therefore, as a result, hence, thus",quiz:{q:"He missed the bus; ___, he was late.",opts:["consequently","consequent","consequence","consequential"],ans:0}},
{en:"Notwithstanding",ph:"/ˌnɒtwɪðˈstændɪŋ/",cn:"尽管，虽然，还是",pos:"介词/副词 prep./adv.",level:"雅思高级",topic:"连接词",ex:{en:"Notwithstanding the challenges, the project was a success.",cn:"尽管面临挑战，该项目还是取得了成功。"},tip:"💡 高级让步表达，给文章加分<br>🔗 同义词：despite, in spite of, although",quiz:{q:"___ the difficulties, they continued.",opts:["Notwithstanding","Notwithstand","Notwithstanded","Notwithstandly"],ans:0}},
{en:"Albeit",ph:"/ɔːlˈbiːɪt/",cn:"尽管，虽然",pos:"连词 conj.",level:"雅思高级",topic:"连接词",ex:{en:"The results were positive, albeit not as strong as expected.",cn:"结果是积极的，尽管没有预期的那么强劲。"},tip:"💡 高分写作词：albeit + adj./adv./从句<br>🔗 使用：The plan worked, albeit slowly.",quiz:{q:"She succeeded, ___ with some difficulty.",opts:["albeit","although","even though","despite"],ans:0}},
{en:"Subsequently",ph:"/ˈsʌbsɪkwəntli/",cn:"随后，接着，其后",pos:"副词 adv.",level:"雅思写作",topic:"连接词",ex:{en:"The law was passed; subsequently, crime rates fell.",cn:"法律通过后，随后犯罪率下降了。"},tip:"💡 表时间顺序，比 then/after 更正式<br>🔗 同族：subsequent（adj.随后的）",quiz:{q:"The medicine was tested and ___ approved.",opts:["subsequently","subsequent","subsequence","subsequential"],ans:0}},
{en:"Predominantly",ph:"/prɪˈdɒmɪnəntli/",cn:"主要地，主导地，占优势地",pos:"副词 adv.",level:"雅思写作",topic:"连接词",ex:{en:"The population is predominantly young in this country.",cn:"这个国家的人口主要是年轻人。"},tip:"💡 predominant（adj.主导的）→ predominantly（adv.）<br>🔗 同义词：mainly, primarily, largely, chiefly",quiz:{q:"The workforce is ___ female.",opts:["predominant","predominately","predominantly","predominance"],ans:2}},

// ===== ADJECTIVES FOR IELTS =====
{en:"Substantial",ph:"/səbˈstænʃəl/",cn:"大量的，实质性的，重要的",pos:"形容词 adj.",level:"雅思高频",topic:"形容词",ex:{en:"There has been a substantial increase in online shopping.",cn:"网购大幅增加。"},tip:"💡 substance（物质/实质）→ substantial（实质性的）<br>🔗 同义词：significant, considerable, notable",quiz:{q:"The report shows a ___ rise in temperatures.",opts:["substance","substantially","substantial","substantiate"],ans:2}},
{en:"Comprehensive",ph:"/ˌkɒmprɪˈhensɪv/",cn:"全面的，综合的，详尽的",pos:"形容词 adj.",level:"雅思核心",topic:"形容词",ex:{en:"The report provides a comprehensive analysis of the issue.",cn:"该报告对该问题进行了全面分析。"},tip:"💡 comprehend（v.理解/包含）→ comprehensive（adj.全面的）<br>🔗 同义词：thorough, exhaustive, complete",quiz:{q:"We need a ___ plan to tackle pollution.",opts:["comprehend","comprehensively","comprehensive","comprehension"],ans:2}},
{en:"Detrimental",ph:"/ˌdetrɪˈmentəl/",cn:"有害的，不利的",pos:"形容词 adj.",level:"雅思高频",topic:"形容词",ex:{en:"Smoking is detrimental to health.",cn:"吸烟对健康有害。"},tip:"💡 detriment（n.损害）→ detrimental（adj.有害的）<br>🔗 同义词：harmful, damaging, adverse；反义词：beneficial",quiz:{q:"Excessive screen time is ___ to children's development.",opts:["detriment","detrimentally","detrimental","detriments"],ans:2}},
{en:"Prevalent",ph:"/ˈprevələnt/",cn:"普遍的，流行的，盛行的",pos:"形容词 adj.",level:"雅思核心",topic:"形容词",ex:{en:"Smartphone addiction is prevalent among teenagers.",cn:"智能手机成瘾在青少年中很普遍。"},tip:"💡 prevail（v.盛行）→ prevalent（adj.普遍的）<br>🔗 同义词：widespread, common, rampant",quiz:{q:"Obesity is becoming increasingly ___ worldwide.",opts:["prevalence","prevail","prevalent","prevailing"],ans:2}},
{en:"Controversial",ph:"/ˌkɒntrəˈvɜːʃəl/",cn:"有争议的，引起争论的",pos:"形容词 adj.",level:"雅思高频",topic:"形容词",ex:{en:"Capital punishment remains a controversial topic in many countries.",cn:"死刑在许多国家仍然是一个有争议的话题。"},tip:"💡 controversy（n.争议）→ controversial（adj.有争议的）<br>🔗 同族：controversially（adv.）、uncontroversial（adj.无争议的）",quiz:{q:"Genetic engineering is a highly ___ issue.",opts:["controversy","controversially","controversial","controversialist"],ans:2}},
{en:"Inevitable",ph:"/ɪnˈevɪtəbl/",cn:"不可避免的，必然的",pos:"形容词 adj.",level:"雅思高频",topic:"形容词",ex:{en:"Change is inevitable in a rapidly developing society.",cn:"在快速发展的社会中，变化是不可避免的。"},tip:"💡 in（不）+ evit（避免）+ able → 无法避免的<br>🔗 同族：inevitably（adv.）、inevitability（n.）",quiz:{q:"Conflict seems ___ when communication breaks down.",opts:["inevitably","inevitability","inevitable","inevitably so"],ans:2}},
{en:"Prosperous",ph:"/ˈprɒspərəs/",cn:"繁荣的，兴旺的，成功的",pos:"形容词 adj.",level:"雅思核心",topic:"形容词",ex:{en:"A prosperous economy creates jobs and improves living standards.",cn:"繁荣的经济创造就业机会并改善生活水平。"},tip:"💡 prosper（v.繁荣）→ prosperous（adj.）<br>🔗 同族：prosperity（n.繁荣）、prosper（v.）",quiz:{q:"The country became ___ through trade.",opts:["prosperity","prosper","prosperous","prosperously"],ans:2}},
{en:"Adequate",ph:"/ˈædɪkwət/",cn:"足够的，适当的，胜任的",pos:"形容词 adj.",level:"雅思核心",topic:"形容词",ex:{en:"All children deserve access to adequate healthcare.",cn:"所有儿童都应该获得足够的医疗保健。"},tip:"💡 adequate ≠ perfect，只是「够用」<br>🔗 反义词：inadequate（不足的）；同义词：sufficient, enough",quiz:{q:"The shelter provides ___ protection from the cold.",opts:["adequately","adequacy","inadequate","adequate"],ans:3}},
{en:"Fundamental",ph:"/ˌfʌndəˈmentəl/",cn:"基本的，根本的，基础的",pos:"形容词/名词 adj./n.",level:"雅思核心",topic:"形容词",ex:{en:"Education is a fundamental right of every child.",cn:"教育是每个孩子的基本权利。"},tip:"💡 fundament（基础）→ fundamental（基本的）<br>🔗 同义词：basic, essential, primary, core",quiz:{q:"Clean water is ___ to human survival.",opts:["fundamentally","fundamentalism","fundamentals","fundamental"],ans:3}},
{en:"Feasible",ph:"/ˈfiːzɪbl/",cn:"可行的，可能的，可实现的",pos:"形容词 adj.",level:"雅思学术",topic:"形容词",ex:{en:"Nuclear fusion is becoming a technically feasible energy source.",cn:"核聚变正在成为技术上可行的能源。"},tip:"💡 feasible = possible to do practically<br>🔗 同义词：viable, practicable, achievable；反义词：infeasible",quiz:{q:"Is it ___ to travel to Mars within 20 years?",opts:["feasibility","feasibly","infeasible","feasible"],ans:3}},

// ===== VERBS FOR IELTS =====
{en:"Alleviate",ph:"/əˈliːvieɪt/",cn:"减轻，缓解，缓和",pos:"动词 v.",level:"雅思高频",topic:"动词",ex:{en:"Exercise can alleviate symptoms of depression.",cn:"运动可以减轻抑郁症状。"},tip:"💡 al + levi（轻）+ ate → 使变轻 → 减轻<br>🔗 同义词：relieve, ease, reduce, mitigate",quiz:{q:"Medicine can ___ pain and discomfort.",opts:["alleviation","alleviating","alleviate","alleviated"],ans:2}},
{en:"Exacerbate",ph:"/ɪɡˈzæsəbeɪt/",cn:"加剧，使恶化，使加重",pos:"动词 v.",level:"雅思高频",topic:"动词",ex:{en:"Poverty can exacerbate mental health problems.",cn:"贫困会加剧心理健康问题。"},tip:"💡 雅思高分词！exacerbate the problem（加剧问题）<br>🔗 同义词：worsen, aggravate, intensify；反义词：alleviate",quiz:{q:"Poor diet can ___ health conditions.",opts:["exacerbation","exacerbate","exacerbated","exacerbating"],ans:1}},
{en:"Mitigate",ph:"/ˈmɪtɪɡeɪt/",cn:"减轻，缓和，降低",pos:"动词 v.",level:"雅思高频",topic:"动词",ex:{en:"Governments must take action to mitigate the effects of climate change.",cn:"各国政府必须采取行动，减轻气候变化的影响。"},tip:"💡 mitigate risks（降低风险）<br>🔗 同义词：reduce, lessen, alleviate, ease",quiz:{q:"We can ___ climate change by reducing emissions.",opts:["mitigation","mitigate","mitigated","mitigating"],ans:1}},
{en:"Advocate",ph:"/ˈædvəkeɪt/",cn:"倡导，支持，主张；倡导者",pos:"动词/名词 v./n.",level:"雅思高频",topic:"动词",ex:{en:"Many scientists advocate for stronger environmental policies.",cn:"许多科学家倡导更强有力的环境政策。"},tip:"💡 advocate for sth（倡导某事）；作名词：an advocate of（...的倡导者）<br>🔗 同族：advocacy（n.倡导）",quiz:{q:"She ___ for equal rights in education.",opts:["advocacy","advocating","advocate","advocates"],ans:3}},
{en:"Implement",ph:"/ˈɪmplɪment/",cn:"实施，执行，贯彻",pos:"动词 v.",level:"雅思核心",topic:"动词",ex:{en:"The government plans to implement new environmental regulations.",cn:"政府计划实施新的环境法规。"},tip:"💡 implement a policy/plan/strategy（实施政策/计划/策略）<br>🔗 同族：implementation（n.实施）",quiz:{q:"It is time to ___ the new strategy.",opts:["implementation","implementing","implement","implemented"],ans:2}},
{en:"Undermine",ph:"/ˌʌndəˈmaɪn/",cn:"削弱，破坏，逐渐损害",pos:"动词 v.",level:"雅思高频",topic:"动词",ex:{en:"Corruption undermines public trust in government.",cn:"腐败破坏了公众对政府的信任。"},tip:"💡 under（下面）+ mine（挖）→ 从下面挖空 → 暗中破坏<br>🔗 同义词：weaken, erode, damage",quiz:{q:"Fake news can ___ democracy.",opts:["undermine","undermined","undermines","undermining"],ans:0}},
{en:"Facilitate",ph:"/fəˈsɪlɪteɪt/",cn:"促进，帮助，使便利",pos:"动词 v.",level:"雅思核心",topic:"动词",ex:{en:"Technology facilitates communication across the globe.",cn:"技术促进了全球通信。"},tip:"💡 facile（容易的）→ facilitate（使容易）<br>🔗 同族：facilitation（n.）、facility（n.设施）",quiz:{q:"Good roads ___ trade between countries.",opts:["facility","facilitate","facilitation","facilitating"],ans:1}},
{en:"Diminish",ph:"/dɪˈmɪnɪʃ/",cn:"减少，降低，削弱",pos:"动词 v.",level:"雅思核心",topic:"动词",ex:{en:"The importance of traditional skills has diminished over time.",cn:"随着时间的推移，传统技能的重要性已经降低。"},tip:"💡 比 reduce 更正式；returning diminishing returns（收益递减）<br>🔗 同义词：decrease, reduce, decline, lessen",quiz:{q:"His authority began to ___ after the scandal.",opts:["diminished","diminishment","diminish","diminishing"],ans:2}},
{en:"Perpetuate",ph:"/pəˈpetʃueɪt/",cn:"使永久化，使持续，延续",pos:"动词 v.",level:"雅思高级",topic:"动词",ex:{en:"Poverty can perpetuate a cycle of disadvantage across generations.",cn:"贫困会使代代相传的不利处境持续下去。"},tip:"💡 perpetual（adj.永久的）→ perpetuate（v.使永久化）<br>🔗 同义词：maintain, sustain, preserve, continue",quiz:{q:"Stereotypes can ___ discrimination.",opts:["perpetuating","perpetuate","perpetual","perpetuation"],ans:1}},
{en:"Attribute",ph:"/əˈtrɪbjuːt/",cn:"归因于，把...归咎于；特性",pos:"动词/名词 v./n.",level:"雅思核心",topic:"动词",ex:{en:"Experts attribute the rise in obesity to poor diet and inactivity.",cn:"专家将肥胖症的上升归因于不良饮食和缺乏运动。"},tip:"💡 attribute A to B（将A归因于B）<br>🔗 同族：attribution（n.归因）；作名词：an attribute of（...的特性）",quiz:{q:"She ___ her success to hard work.",opts:["attributed","attribution","attribute","attributing"],ans:0}},

// ===== ABSTRACT NOUNS =====
{en:"Implication",ph:"/ˌɪmplɪˈkeɪʃən/",cn:"含义，暗示，影响",pos:"名词 n.",level:"雅思核心",topic:"抽象名词",ex:{en:"The implications of climate change for future generations are severe.",cn:"气候变化对后代的影响是严重的。"},tip:"💡 imply（v.暗示）→ implication（n.含义/影响）<br>🔗 常用：have implications for（对...有影响）",quiz:{q:"The study has serious ___ for public health policy.",opts:["imply","implied","implication","implications"],ans:3}},
{en:"Consequence",ph:"/ˈkɒnsɪkwəns/",cn:"结果，后果，影响",pos:"名词 n.",level:"雅思高频",topic:"抽象名词",ex:{en:"The consequences of deforestation include flooding and soil erosion.",cn:"森林砍伐的后果包括洪水和土壤侵蚀。"},tip:"💡 as a consequence（因此）；have consequences（有后果）<br>🔗 同族：consequent（adj.随之而来的）、consequently（adv.）",quiz:{q:"What are the ___ of not exercising regularly?",opts:["consequent","consequently","consequences","consequence"],ans:2}},
{en:"Phenomenon",ph:"/fɪˈnɒmɪnən/",cn:"现象，奇迹",pos:"名词 n.",level:"雅思核心",topic:"抽象名词",ex:{en:"Social media is a relatively new phenomenon.",cn:"社交媒体是一种相对较新的现象。"},tip:"💡 复数：phenomena；natural phenomenon（自然现象）<br>🔗 同族：phenomenal（adj.非凡的）",quiz:{q:"Global warming is a worldwide ___.",opts:["phenomenal","phenomena","phenomenon","phenomenons"],ans:2}},
{en:"Perspective",ph:"/pəˈspektɪv/",cn:"观点，角度，看法；透视",pos:"名词 n.",level:"雅思核心",topic:"抽象名词",ex:{en:"It is important to consider different perspectives on this issue.",cn:"从不同角度考虑这个问题很重要。"},tip:"💡 from a...perspective（从...角度来看）<br>🔗 同义词：viewpoint, standpoint, angle",quiz:{q:"We should consider the issue from multiple ___.",opts:["perspective","perspectivism","perspectives","perspectively"],ans:2}},
{en:"Transition",ph:"/trænˈzɪʃən/",cn:"过渡，转变，变迁",pos:"名词/动词 n./v.",level:"雅思核心",topic:"抽象名词",ex:{en:"The transition from fossil fuels to renewable energy will take decades.",cn:"从化石燃料过渡到可再生能源需要数十年时间。"},tip:"💡 transit（通过）→ transition（过渡）<br>🔗 同族：transitional（adj.过渡的）、transit（n.运输）",quiz:{q:"The ___ to democracy was peaceful.",opts:["transit","transitional","transition","transitioned"],ans:2}},
{en:"Perception",ph:"/pəˈsepʃən/",cn:"感知，看法，认知",pos:"名词 n.",level:"雅思核心",topic:"抽象名词",ex:{en:"Public perception of climate change has shifted in recent years.",cn:"近年来公众对气候变化的看法发生了转变。"},tip:"💡 perceive（v.感知）→ perception（n.感知/看法）<br>🔗 同族：perceptive（adj.有洞察力的）、perceive（v.）",quiz:{q:"Our ___ of risk affects our decisions.",opts:["perceive","perceptive","perception","percept"],ans:2}},
{en:"Circumstance",ph:"/ˈsɜːkəmstæns/",cn:"情况，情形，环境",pos:"名词 n.",level:"雅思核心",topic:"抽象名词",ex:{en:"In some circumstances, lying may be the kindest option.",cn:"在某些情况下，说谎可能是最善意的选择。"},tip:"💡 under the circumstances（在这种情况下）<br>🔗 同义词：situation, condition, context",quiz:{q:"We must adapt to changing ___.",opts:["circumstantial","circumstance","circumstances","circumstanced"],ans:2}},
{en:"Assumption",ph:"/əˈsʌmpʃən/",cn:"假设，设想，假定",pos:"名词 n.",level:"雅思核心",topic:"抽象名词",ex:{en:"The theory is based on the assumption that all people are rational.",cn:"该理论基于所有人都是理性的假设。"},tip:"💡 assume（v.假设）→ assumption（n.）<br>🔗 常用：make an assumption（做出假设）",quiz:{q:"We should not make ___ without evidence.",opts:["assume","assumed","assumptions","assumption"],ans:3}},
{en:"Contradiction",ph:"/ˌkɒntrəˈdɪkʃən/",cn:"矛盾，相悖，反驳",pos:"名词 n.",level:"雅思学术",topic:"抽象名词",ex:{en:"There is a contradiction between what he says and what he does.",cn:"他说的和他做的之间存在矛盾。"},tip:"💡 contradict（v.与...矛盾）→ contradiction（n.）<br>🔗 同族：contradictory（adj.矛盾的）",quiz:{q:"His actions are in ___ with his stated values.",opts:["contradict","contradictory","contradiction","contradicting"],ans:2}},
{en:"Integrity",ph:"/ɪnˈteɡrɪti/",cn:"诚信，正直，完整性",pos:"名词 n.",level:"雅思核心",topic:"抽象名词",ex:{en:"A good leader must demonstrate integrity in all their decisions.",cn:"好的领导者必须在所有决策中展现诚信。"},tip:"💡 integer（整数/完整）→ integrity（完整性/正直）<br>🔗 同义词：honesty, probity, morality",quiz:{q:"Academic ___ means not cheating or plagiarising.",opts:["integrate","integrated","integrity","integration"],ans:2}}
];

// Export for use in main file
if(typeof module !== 'undefined') module.exports = WORD_DB;

// ===== BATCH 2: MORE IELTS CORE WORDS =====
// Adding words to reach ~300 high quality entries
